name-template: "Release $RESOLVED_VERSION"
tag-template: "$RESOLVED_VERSION"

# Categories match exactly with PR labels from labeler.yml
categories:
  - title: "🚀 New Features"
    labels:
      - "feature"
      - "enhancement"

  - title: "🎮 Game Development"
    labels:
      - "game-logic"
      - "graphics"
      - "audio"
      - "pixi-components"

  - title: "🎨 UI/UX Improvements"
    labels:
      - "ui"
      - "design"
      - "style"

  - title: "🏗️ Infrastructure & Performance"
    labels:
      - "infrastructure"
      - "performance"
      - "build"
      - "config"

  - title: "🔄 Code Quality & Refactoring"
    labels:
      - "refactor"
      - "testing"
      - "types"

  - title: "🔒 Security & Compliance"
    labels:
      - "security"

  - title: "📝 Documentation"
    labels:
      - "documentation"

  - title: "📦 Dependencies"
    labels:
      - "dependencies"
      - "javascript"
      - "github_actions"
    
  - title: "🐛 Bug Fixes"
    labels:
      - "bug"
      - "fix"

  - title: "🧪 Test Coverage Improvements"
    labels:
      - "test-coverage-impact"
      - "needs-tests"
      - "high-coverage"
      - "e2e"

  - title: "🎨 Assets & Resources"
    labels:
      - "assets"

  - title: "🔧 Development Environment"
    labels:
      - "devcontainer"

  - title: "⚙️ Component Updates"
    labels:
      - "component-app"
      - "component-main"
      - "component-game"
      - "component-ui"

change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&' # Escape markdown special characters


template: |
  # Highlights
  $CHANGES

  ## Security & Quality
  [![OpenSSF Scorecard](https://api.securityscorecards.dev/projects/github.com/Hack23/game/badge)](https://scorecard.dev/viewer/?uri=github.com/Hack23/game)

  ## Security Compliance
  [![SLSA 3](https://slsa.dev/images/gh-badge-level3.svg)](https://github.com/Hack23/game/attestations/)

  ## Game Development Stack
  - ⚡ **Vite** - Fast build tool and dev server
  - ⚛️ **React 19** - Modern React with hooks  
  - 🔷 **TypeScript** - Strict typing with latest standards
  - 🎮 **PixiJS 8.x** - High-performance WebGL renderer
  - 🎵 **Howler.js** - Audio library for games
  - 🧪 **Vitest** - Fast unit testing with coverage
  - 🌲 **Cypress** - Reliable E2E testing

  ## Contributors
  Thanks to $CONTRIBUTORS for their contributions to this release!

  **Full Changelog**: https://github.com/Hack23/game/compare/$PREVIOUS_TAG...$RESOLVED_VERSION

version-resolver:
  major:
    labels:
      - "major"
      - "breaking"
  minor:
    labels:
      - "feature"
      - "enhancement"
      - "game-logic"
      - "graphics"
      - "audio"
      - "pixi-components"
  patch:
    labels:
      - "bug"
      - "fix"
      - "security"
      - "dependencies"
      - "documentation"
      - "performance"
      - "refactor"
  default: patch

# Autolabeler is BACKUP for PRs without labels
# Primary labeling happens via .github/labeler.yml
autolabeler:
  # Features & Enhancements
  - label: "feature"
    title:
      - '/^feat(\([^)]+\))?:/i'
      - '/^feature(\([^)]+\))?:/i'
      - '/^add(\([^)]+\))?:/i'
  
  - label: "enhancement"
    title:
      - '/^enhance(\([^)]+\))?:/i'
      - '/^improve(\([^)]+\))?:/i'
      - '/^improvement(\([^)]+\))?:/i'
  
  # Bug Fixes
  - label: "bug"
    title:
      - '/^fix(\([^)]+\))?:/i'
      - '/^bug(\([^)]+\))?:/i'
      - '/^bugfix(\([^)]+\))?:/i'
  
  - label: "fix"
    title:
      - '/^fix(\([^)]+\))?:/i'
  
  # Documentation
  - label: "documentation"
    title:
      - '/^docs(\([^)]+\))?:/i'
      - '/^doc(\([^)]+\))?:/i'
    files:
      - '**/*.md'
      - 'docs/**/*'
      - '**/*.mdx'
  
  # UI/UX
  - label: "ui"
    title:
      - '/^ui(\([^)]+\))?:/i'
    files:
      - 'src/**/components/**/*'
      - 'src/**/ui/**/*'
  
  - label: "design"
    title:
      - '/^design(\([^)]+\))?:/i'
  
  - label: "style"
    title:
      - '/^style(\([^)]+\))?:/i'
    files:
      - '**/*.css'
      - '**/*.scss'
      - '**/*.less'
      - '**/*.styles.*'
  
  # Dependencies - CRITICAL FOR DEPENDABOT/RENOVATE
  - label: "dependencies"
    title:
      - '/^build\(deps\):/i'
      - '/^build\(deps-dev\):/i'
      - '/^chore\(deps\):/i'
      - '/^chore\(deps-dev\):/i'
      - '/^deps(\([^)]+\))?:/i'
      - '/^dependency(\([^)]+\))?:/i'
      - '/^dependencies(\([^)]+\))?:/i'
      - '/^bump/i'
      - '/^update.*dependenc/i'
      - '/^upgrade.*dependenc/i'
  
  # Security
  - label: "security"
    title:
      - '/^security(\([^)]+\))?:/i'
      - '/^sec(\([^)]+\))?:/i'
      - '/^fix-vuln(\([^)]+\))?:/i'
      - '/\[security\]/i'
  
  # Performance
  - label: "performance"
    title:
      - '/^perf(\([^)]+\))?:/i'
      - '/^optimize(\([^)]+\))?:/i'
  
  # Infrastructure
  - label: "infrastructure"
    title:
      - '/^infra(\([^)]+\))?:/i'
      - '/^ci(\([^)]+\))?:/i'
      - '/^cd(\([^)]+\))?:/i'
    files:
      - '.github/**/*'
      - 'scripts/**/*'
      - 'docker/**/*'
  
  - label: "build"
    title:
      - '/^build(\([^)]+\))?:/i'
      - '/^chore\(build\):/i'
    files:
      - 'vite.config.*'
      - 'vitest.config.*'
      - 'tsconfig.json'
      - 'webpack.config.*'
  
  - label: "config"
    title:
      - '/^config(\([^)]+\))?:/i'
      - '/^chore\(config\):/i'
    files:
      - '**/*.config.*'
      - '**/eslint.config.*'
      - '**/tsconfig*.json'
  
  # Code Quality
  - label: "refactor"
    title:
      - '/^refactor(\([^)]+\))?:/i'
  
  - label: "testing"
    title:
      - '/^test(\([^)]+\))?:/i'
    files:
      - '**/*.test.*'
      - '**/*.spec.*'
      - 'cypress/**/*'
      - '__tests__/**/*'
      - 'test/**/*'
  
  - label: "types"
    title:
      - '/^types(\([^)]+\))?:/i'
      - '/^type(\([^)]+\))?:/i'
    files:
      - '**/*.d.ts'
      - 'src/types/**/*'
  
  # Game Development
  - label: "game-logic"
    title:
      - '/^game(\([^)]+\))?:/i'
      - '/^logic(\([^)]+\))?:/i'
      - '/^mechanics(\([^)]+\))?:/i'
    files:
      - 'src/**/game/**/*'
      - 'src/**/logic/**/*'
      - 'src/**/mechanics/**/*'
  
  - label: "graphics"
    title:
      - '/^graphics(\([^)]+\))?:/i'
      - '/^pixi(\([^)]+\))?:/i'
      - '/^render(\([^)]+\))?:/i'
    files:
      - 'src/**/graphics/**/*'
      - 'src/**/pixi/**/*'
      - 'src/**/render/**/*'
  
  - label: "audio"
    title:
      - '/^audio(\([^)]+\))?:/i'
      - '/^sound(\([^)]+\))?:/i'
    files:
      - 'src/**/audio/**/*'
      - 'src/**/sound/**/*'
      - '**/*howler*'
      - '**/*.mp3'
      - '**/*.wav'
      - '**/*.ogg'
  
  - label: "pixi-components"
    title:
      - '/^pixi(\([^)]+\))?:/i'
    files:
      - 'src/**/*pixi*'
      - 'src/**/*Pixi*'
  
  # Test Coverage
  - label: "test-coverage-impact"
    files:
      - '**/*.test.{ts,tsx}'
      - '**/__tests__/**'
  
  - label: "needs-tests"
    files:
      - 'src/components/**/*'
      - 'src/hooks/**/*'
  
  - label: "high-coverage"
    files:
      - 'src/App.tsx'
      - 'src/main.tsx'
  
  - label: "e2e"
    title:
      - '/^e2e(\([^)]+\))?:/i'
      - '/end.?to.?end/i'
    files:
      - 'cypress/**/*'
      - '**/*.cy.*'
  
  # Assets
  - label: "assets"
    title:
      - '/^assets(\([^)]+\))?:/i'
    files:
      - 'src/assets/**/*'
      - 'public/**/*.png'
      - 'public/**/*.jpg'
      - 'public/**/*.svg'
      - 'public/**/*.mp3'
      - 'public/**/*.wav'
      - 'public/**/*.ogg'
  
  # DevContainer
  - label: "devcontainer"
    title:
      - '/devcontainer/i'
    files:
      - '.devcontainer/**/*'
      - '.codespaces/**/*'
  
  # Component-specific labels
  - label: "component-app"
    files:
      - 'src/App.tsx'
  
  - label: "component-main"
    files:
      - 'src/main.tsx'
  
  - label: "component-game"
    files:
      - 'src/components/Game.tsx'
  
  - label: "component-ui"
    files:
      - 'src/components/UI/**/*'
