name: "Pull Request Automatic Labeler"

on:
  pull_request_target:
    types: [opened, synchronize, reopened, edited]

# Set default permissions to read-only
permissions: read-all

jobs:
  labeler:
    name: Label Pull Request
    runs-on: ubuntu-latest
    # Only this job needs specific permissions
    permissions:
      contents: read # Required to check out the code
      pull-requests: write # Required to apply labels to PRs
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit

      - name: Apply PR Labels
        uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9 # v5.0.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: true
          configuration-path: .github/labeler.yml
